all:
	g++ -std=c++11 -Wall -g -O0 mp3.cpp lodepng.cpp -lGL -lGLU -lglut -o mp3

test:
	./mp3 teapot_0.obj images/blue_tile.png images/uffizi_probe.png

#lighting:
#	g++ -std=c++11 -Wall -g -O0 lighting.cpp -lGL -lGLU -lglut -o lighting

clean: 
	rm mp3 lighting
